import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ProductCard from '../Components/ProductCard'
import Grid from '@mui/material/Grid';
import NavBar from '../Components/NavBar'

export default function Home({ 
    products 
  }: {
    products: {
      category: string
      description: string
      id: number
      image: string
      price: number
      title: string
      rating: {
        rate: number
        count: number
      }
    }
  }) {

  const [ product, setProduct ] = useState([])
  let tmpArray = JSON.parse(JSON.stringify(product))

  const addProduct = item => {
    tmpArray.push(item)
    setProduct(tmpArray)
  }

  const resetProducts = () => {
    setProduct([])
  }
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <NavBar  cleanFilter={resetProducts} product={product} />
      <main>
        
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
          <button onClick={resetProducts} >reset</button>
        </p>

        <Grid container spacing={2}>
          {
            products.map( (p, id) => (
              <Grid key={id} item xs={3}>
                <ProductCard 
                handleSelected={() => addProduct(p)} 
                data={p} />
              </Grid>
            ))
          }
        </Grid>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps() {
  const res = await fetch(`https://fakestoreapi.com/products`)
  const products = await res.json()

  return {
    props: { products },
    revalidate: 1,
  }
}